/* tslint:disable */
/* eslint-disable */
//----------------------
// <auto-generated>
//   Generated using Swaggie (https://github.com/yhnavein/swaggie)
//   Please avoid doing any manual changes in this file
// </auto-generated>
//----------------------
// ReSharper disable InconsistentNaming

import Axios, { AxiosPromise, AxiosRequestConfig } from "axios";

export const axios = Axios.create({
  baseURL: "",
});

export const employeesClient = {
  /**
   */
  getApiEmployees(
    $config?: AxiosRequestConfig
  ): AxiosPromise<GetEmployeesQueryResult[]> {
    let url = "/api/Employees";

    return axios.request<GetEmployeesQueryResult[]>({
      url: url,
      method: "GET",
      ...$config,
    });
  },
};

function serializeQueryParam(obj: any) {
  if (obj === null || obj === undefined) return "";
  if (obj instanceof Date) return obj.toJSON();
  if (typeof obj !== "object" || Array.isArray(obj)) return obj;
  return Object.keys(obj)
    .reduce((a: any, b) => a.push(b + "=" + obj[b]) && a, [])
    .join("&");
}

export interface GetEmployeesQueryResult {
  firstName?: string;
  lastName?: string;
}
